exchange: binance
timeframe: 3m
symbols: [“BTC/USDT”,“ETH/USDT”,“SOL/USDT”,“LINK/USDT”,“AKT/USDT”,“ZEC/USDT”]
poll_seconds: 60

Universe scanner

universe: [“BTC/USDT”,“ETH/USDT”,“SOL/USDT”,“LINK/USDT”,“ZEC/USDT”,“ADA/USDT”,“DOGE/USDT”]
focus_top_k: 14
focus_buffer: 8
consec_scans_to_enter: 2
consec_scans_to_drop: 2
scan_interval_sec: 60

enter:
 vdelta_min: 2.0
 vrr_min: 1.5
 rsi_max: 65
 macd_hist_up2: true

exit:
 vt_min: 0.20
 rsi_min: 70
 macd_hist_dn2: true

transfer:
 vrr_min: 1.3
 vdelta_min: 0.5

start_equity: 10000
cap_fraction: 0.25
fee_bps: 10
slip_bps: 20
hard_stop_pct: 0.02
daily_loss_cap_pct: 0.05
cost_haircut_on_gains_pct: 0.10
log_csv: true

ai:
 enabled: false
 model_path: models/surf_xgb.pkl
 pmin: 0.65
 size_gain: 0.4
